server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clinic_auth_db
    username: root
    password: MyClinic2025!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  application:
    name: auth-service

jwt:
  secret: "tu_clave_secreta_super_segura_de_mas_de_32_caracteres"
  expiration: 86400000 # 1 día en milisegundos

