# Etapa 1: Build
FROM node:20 AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build --prod

# Etapa 2: Imagen de producción con NGINX
FROM nginx:alpine

COPY --from=build /app/dist/clinic-frontend /usr/share/nginx/html

# Copiamos configuración personalizada de nginx si la tienes
# COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
